# 基础RNN

## RNNCell
这个要自己写循环，因为输入是一个个序列

In [1]:
import torch

batch_size = 1
# 序列的个数
seq_len = 3
# 每个序列元素的维度
input_size = 4
# 隐层的维度
hidden_size = 2

# 这一次的输入，加上上一次的隐层
cell = torch.nn.RNNCell(input_size=input_size,hidden_size=hidden_size)

# (seq,batch,features)
dataset = torch.randn(seq_len,batch_size,input_size)
dataset

tensor([[[-0.7947, -0.6821,  0.5168,  0.7511]],

        [[-0.4426,  0.4632, -0.6277, -1.9453]],

        [[-0.0390, -1.2800, -0.5796, -0.4423]]])

In [2]:
# 初始值为全零
hidden = torch.zeros(batch_size,hidden_size)
hidden

tensor([[0., 0.]])

In [5]:
# 自己写循环，一个个序列训练
for idx,input in enumerate(dataset):
    print('='*20,idx,'='*20)
    print('input size:',input.shape)
    print(input)
    # 这里的input只是一个序列，而RNN模块的input是整个序列
    hidden = cell(input,hidden)
    print('outputs size:',hidden.shape)
    print(hidden)

==================== 0 ====================
input size: torch.Size([1, 4])
tensor([[-0.7947, -0.6821,  0.5168,  0.7511]])
outputs size: torch.Size([1, 2])
tensor([[ 0.2991, -0.0042]], grad_fn=<TanhBackward0>)
==================== 1 ====================
input size: torch.Size([1, 4])
tensor([[-0.4426,  0.4632, -0.6277, -1.9453]])
outputs size: torch.Size([1, 2])
tensor([[ 0.9739, -0.7383]], grad_fn=<TanhBackward0>)
==================== 2 ====================
input size: torch.Size([1, 4])
tensor([[-0.0390, -1.2800, -0.5796, -0.4423]])
outputs size: torch.Size([1, 2])
tensor([[0.8112, 0.8467]], grad_fn=<TanhBackward0>)


## RNN模块
不用自己写循环，因为是全部序列一起送进去训练的

In [22]:
import torch

batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2
num_layers = 2

# 相比RNN Cell 多了一个num_layers参数
cell = torch.nn.RNN(input_size=input_size,hidden_size=hidden_size,num_layers=num_layers)
# 有两层，所以有 L0 和L1
cell._parameters.keys()

odict_keys(['weight_ih_l0', 'weight_hh_l0', 'bias_ih_l0', 'bias_hh_l0', 'weight_ih_l1', 'weight_hh_l1', 'bias_ih_l1', 'bias_hh_l1'])

In [23]:
# (seqLen,batchSize,inputSize)
inputs = torch.randn(seq_len,batch_size,input_size)
inputs

tensor([[[ 0.5733, -2.0924, -0.0403,  0.4757]],

        [[ 0.9369,  1.4870, -2.5997,  0.4912]],

        [[ 0.1648,  1.5491, -0.4033,  1.4957]]])

In [24]:
# 多了一层num_layer
hidden = torch.zeros(num_layers,batch_size,hidden_size)
hidden

tensor([[[0., 0.]],

        [[0., 0.]]])

In [25]:
# 不用循环
# inputs全部序列
out,hidden = cell(inputs,hidden)

# (seqSize,batchSize,hiddenSize)
print('Output size:',out.shape)
print('Output:',out)
# (numLayers,batchSize,hiddenSize)
print('Hidden size:',hidden.shape)
print('Hidden:',hidden)

Output size: torch.Size([3, 1, 2])
Output: tensor([[[ 0.7328,  0.0594]],

        [[ 0.9721, -0.1198]],

        [[ 0.9592, -0.4367]]], grad_fn=<StackBackward0>)
Hidden size: torch.Size([2, 1, 2])
Hidden: tensor([[[-0.6193, -0.8778]],

        [[ 0.9592, -0.4367]]], grad_fn=<StackBackward0>)
