In [146]:
import torch

In [5]:
torch.cuda.is_available()

False

In [6]:
torch.backends.cudnn.enabled

True

In [7]:
# 查看pytorch有什么工具箱
dir(torch)

['AVG',
 'AggregationType',
 'AliasDb',
 'AnyType',
 'Argument',
 'ArgumentSpec',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BenchmarkConfig',
 'BenchmarkExecutionStats',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'BufferDict',
 'ByteStorage',
 'ByteTensor',
 'CONV_BN_FUSION',
 'CallStack',
 'Capsule',
 'CharStorage',
 'CharTensor',
 'ClassType',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'ComplexDoubleStorage',
 'ComplexFloatStorage',
 'ComplexType',
 'ConcreteModuleType',
 'ConcreteModuleTypeBuilder',
 'CudaByteStorageBase',
 'DeepCopyMemoTable',
 'DeserializationStorageContext',
 'DeviceObjType',
 'DictType',
 'DisableTorchFunction',
 'DoubleStorage',
 'DoubleTensor',
 'EnumType',
 'ErrorReport',
 'ExecutionPlan',
 'FUSE_ADD_RELU',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'FunctionSchema',
 'Future',
 'FutureType',
 'Generator',
 'Gradient',
 'Graph',
 'GraphExecutorState',
 'HOIST_CONV_PACKED_PARAMS',
 'HalfStorage',
 'HalfT

In [8]:
# 查看torch里面的cuda有什么工具箱,可以看到is_available
dir(torch.cuda)

['Any',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BoolStorage',
 'BoolTensor',
 'ByteStorage',
 'ByteTensor',
 'CUDAGraph',
 'CharStorage',
 'CharTensor',
 'ComplexDoubleStorage',
 'ComplexFloatStorage',
 'CudaError',
 'DeferredCudaCallError',
 'Device',
 'Dict',
 'DoubleStorage',
 'DoubleTensor',
 'Event',
 'ExternalStream',
 'FloatStorage',
 'FloatTensor',
 'HalfStorage',
 'HalfTensor',
 'IntStorage',
 'IntTensor',
 'List',
 'LongStorage',
 'LongTensor',
 'Optional',
 'ShortStorage',
 'ShortTensor',
 'Stream',
 'StreamContext',
 'Tuple',
 'Union',
 '_CudaBase',
 '_CudaDeviceProperties',
 '_LazySeedTracker',
 '_StorageBase',
 '_TypedStorage',
 '_UntypedStorage',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_check_capability',
 '_check_cubins',
 '_cudart',
 '_device',
 '_device_t',
 '_dummy_type',
 '_get_device_index',
 '_initialization_lock',
 '_initialized',
 '_is_in_bad_fork',
 '_l

In [9]:
# 查看torch.cuda.is_available里面的工具箱
# __双下划线表示里面的是函数变量不可变不可修改
dir(torch.cuda.is_available)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [10]:
# 查看用法
help(torch.cuda.is_available)

Help on function is_available in module torch.cuda:

is_available() -> bool
    Returns a bool indicating if CUDA is currently available.



In [1]:
from torch.utils.data import Dataset

In [8]:
help(Dataset)

Help on class Dataset in module torch.utils.data.dataset:

class Dataset(typing.Generic)
 |  Dataset(*args, **kwds)
 |  
 |  An abstract class representing a :class:`Dataset`.
 |  
 |  All datasets that represent a map from keys to data samples should subclass
 |  it. All subclasses should overwrite :meth:`__getitem__`, supporting fetching a
 |  data sample for a given key. Subclasses could also optionally overwrite
 |  :meth:`__len__`, which is expected to return the size of the dataset by many
 |  :class:`~torch.utils.data.Sampler` implementations and the default options
 |  of :class:`~torch.utils.data.DataLoader`.
 |  
 |  .. note::
 |    :class:`~torch.utils.data.DataLoader` by default constructs a index
 |    sampler that yields integral indices.  To make it work with a map-style
 |    dataset with non-integral indices/keys, a custom sampler must be provided.
 |  
 |  Method resolution order:
 |      Dataset
 |      typing.Generic
 |      builtins.object
 |  
 |  Methods defined 

In [9]:
Dataset??

In [2]:
import numpy as np

In [4]:
t1 = np.arange(24).reshape((6,4))
t1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
t2 = np.arange(100,124).reshape((6,4))
t2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123]])

In [8]:
print(t1+t2)
print(t1*t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [9]:
t2 = np.arange(0,6)
t2

array([0, 1, 2, 3, 4, 5])

In [11]:
t1 = np.arange(0,24).reshape(4,6)
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
t1 + t2

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16],
       [12, 14, 16, 18, 20, 22],
       [18, 20, 22, 24, 26, 28]])

In [13]:
t3 = np.arange(4).reshape(4,1)
t3

array([[0],
       [1],
       [2],
       [3]])

In [15]:
t1 + t3

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26]])

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.append(a,[[7,8,9],[10,11,12]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.append(a,[[5,5],[6,6]],axis=1)

array([[1, 2, 3, 5, 5],
       [4, 5, 6, 6, 6]])

In [28]:
import torch
x = torch.empty(5,3)
x

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22],
        [2.1715e-18, 2.1161e-07, 6.7126e-07],
        [8.2733e+20, 3.3237e+21, 1.6520e-04]])

In [29]:
x = torch.rand(5,3)
x

tensor([[0.4497, 0.4502, 0.6884],
        [0.5651, 0.7263, 0.4247],
        [0.9453, 0.1676, 0.7574],
        [0.0711, 0.5405, 0.4692],
        [0.9445, 0.9967, 0.1637]])

In [31]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [32]:
x = torch.tensor([5.5000,3.0000])
x

tensor([5.5000, 3.0000])

In [34]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [39]:
x = torch.rand_like(x)
x

tensor([[0.7572, 0.7440, 0.3584],
        [0.5905, 0.9170, 0.9294],
        [0.4617, 0.9569, 0.8635],
        [0.7150, 0.7602, 0.6920],
        [0.0264, 0.6339, 0.0375]], dtype=torch.float64)

In [42]:
x.size()

torch.Size([5, 3])

In [44]:
torch.Size([5,3])

torch.Size([5, 3])

In [46]:
y = torch.rand(5,3)
y

tensor([[0.2677, 0.1299, 0.1890],
        [0.6326, 0.1407, 0.3221],
        [0.3323, 0.8445, 0.7135],
        [0.0367, 0.9599, 0.2367],
        [0.4054, 0.4392, 0.3517]])

In [47]:
x + y

tensor([[1.0250, 0.8739, 0.5474],
        [1.2231, 1.0577, 1.2514],
        [0.7940, 1.8014, 1.5770],
        [0.7517, 1.7201, 0.9288],
        [0.4319, 1.0731, 0.3892]], dtype=torch.float64)

In [48]:
torch.add(x,y)

tensor([[1.0250, 0.8739, 0.5474],
        [1.2231, 1.0577, 1.2514],
        [0.7940, 1.8014, 1.5770],
        [0.7517, 1.7201, 0.9288],
        [0.4319, 1.0731, 0.3892]], dtype=torch.float64)

In [51]:
x = torch.rand(4,4)
y = x.view(16)
z = y.view(8,2)
z

tensor([[0.1299, 0.4633],
        [0.2712, 0.2878],
        [0.4780, 0.7575],
        [0.1674, 0.1296],
        [0.7508, 0.2605],
        [0.8407, 0.2996],
        [0.9600, 0.6874],
        [0.5020, 0.1798]])

In [68]:
x = torch.randn(1)
x.item()

-1.4848886728286743

In [77]:
import torch.nn.functional as F
torch.randn??
torch.ones??
torch.full??
F.mse_loss??
torch.autograd.grad??

In [95]:
import torch
import torch.nn.functional as F
# 对 pred = xw + b进行求导,初始化 x=1,w=2,b=0
x = torch.ones(1)
w = torch.full([1],2)

# mse_loss第一参数是预测的值，第二个参数是真实值
MSE = F.mse_loss(x*w,torch.ones(1)) # MSE = 1

# 表示MSE对w求导
torch.autograd.grad(MSE,[w])

NameError: name 'float64' is not defined

In [96]:
#w.requires_grad_()
w.requires_grad_() # tensor([2.], requires_grad=True) 设置w的梯度 不然会报错
MSE = F.mse_loss(x*w,torch.ones(1)) # MSE = 1
# 表示MSE对w求导
#torch.autograd.grad(MSE,[w])
MSE.backward()

RuntimeError: Found dtype Float but expected Double

In [112]:
# x的特征有10个
x = torch.randn(1,10)
w = torch.randn(1,10,requires_grad=True)
o = torch.sigmoid(x@w.t()) # t()表示转置，答案是一个数
o

tensor([[0.9514]], grad_fn=<SigmoidBackward0>)

In [113]:
loss = F.mse_loss(torch.ones(1,1),o)
loss.backward()
w.grad

tensor([[-0.0058,  0.0020, -0.0031, -0.0031, -0.0013, -0.0009,  0.0004,  0.0009,
          0.0035,  0.0066]])

In [126]:
x.shape
x.t().shape

torch.Size([10, 1])

In [127]:
z = torch.linspace(-100,100,10)
torch.sigmoid(z)

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

In [135]:
import torch
import torch.nn.functional as F
x = torch.randn(1,10) # 1行10列
w = torch.randn(2,10,requires_grad=True) # 2行10列
o = torch.sigmoid(x@w.t()) # @这个符号表示是按照矩阵运算的乘积的形式，不是单纯的对应元素相乘。所以o是一个1行2列的数torch.Size([1, 2])
loss = F.mse_loss(torch.ones(1,2),o)
loss.backward() # 对权值w求导
w.grad # 取出对w求导后的值，2行10列

tensor([[ 0.0561,  0.0070,  0.0154,  0.1262,  0.0777, -0.0880,  0.2638, -0.1206,
         -0.1128,  0.1552],
        [ 0.0378,  0.0047,  0.0104,  0.0851,  0.0524, -0.0593,  0.1778, -0.0813,
         -0.0760,  0.1046]])

In [143]:
# 链式法则验证
x = torch.tensor(1.)
w1 = torch.tensor(2.,requires_grad=True)
b1 = torch.tensor(1.)
w2 = torch.tensor(2.,requires_grad=True)
b2 = torch.tensor(1.)

y1 = x * w1 + b1
y2 = y1 * w2 + b2

# y2对y1求导
dy2_dy1 = torch.autograd.grad(y2,[y1],retain_graph=True)[0]
# y1对w1求导
dy1_dw1 = torch.autograd.grad(y1,[w1],retain_graph=True)[0]
# y2直接对W1求导
dy2_dw1 = torch.autograd.grad(y2,[w1],retain_graph=True)[0]

# 看两者是否相同
dy2_dw1 == dy2_dy1 * dy1_dw1 # 返回true

tensor(True)

In [145]:
import torch
print(torch.__version__)

1.11.0


In [161]:
x = torch.tensor([1.,2.])
# print(type(x.item()))
print(x.data[1])
print(x.numpy()[1])

tensor(2.)
2.0


In [171]:
import torch
a = torch.tensor([1,2,3.], requires_grad = True)
print(a)

tensor([1., 2., 3.], requires_grad=True)


In [169]:
b = a.data
print(b.requires_grad)
print(b)

False
tensor([1., 2., 3.])


In [170]:
c = a.detach()
print(c.requires_grad)
print(c)

False
tensor([1., 2., 3.])


In [173]:
a = torch.tensor([1,2,3.], requires_grad = True)
c = a.data  # 需要走注意的是，通过.data “分离”得到的的变量会和原来的变量共用同样的数据，而且新分离得到的张量是不可求导的，c发生了变化，原来的张量也会发生变化
print(a) # tensor([1., 2., 3.], requires_grad=True)
c.zero_() # c发生变化
print(a) # tensor([0., 0., 0.], requires_grad=True)

tensor([1., 2., 3.], requires_grad=True)
tensor([0., 0., 0.], requires_grad=True)


In [174]:
a = torch.tensor([1,2,3.], requires_grad = True)
c = a.detach()  # 需要走注意的是，通过.data “分离”得到的的变量会和原来的变量共用同样的数据，而且新分离得到的张量是不可求导的，c发生了变化，原来的张量也会发生变化
print(a) # tensor([1., 2., 3.], requires_grad=True)
c.zero_() # c发生变化
print(a) # tensor([0., 0., 0.], requires_grad=True)

tensor([1., 2., 3.], requires_grad=True)
tensor([0., 0., 0.], requires_grad=True)


In [175]:

import torch
 
a = torch.tensor([1,2,3.], requires_grad = True)
out = a.sigmoid()
c = out.data  # 需要走注意的是，通过.data “分离”得到的的变量会和原来的变量共用同样的数据，而且新分离得到的张量是不可求导的，c发生了变化，原来的张量也会发生变化
c.zero_()     # 改变c的值，原来的out也会改变
print(c.requires_grad)
print(c)
print(out.requires_grad)
print(out)
print("----------------------------------------------")
out.sum().backward() # 对原来的out求导，
print(a.grad)  # 不会报错，但是结果却并不正确

False
tensor([0., 0., 0.])
True
tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)
----------------------------------------------
tensor([0., 0., 0.])


In [176]:
import torch
 
a = torch.tensor([1,2,3.], requires_grad = True)
out = a.sigmoid()
c = out.detach()  # 需要走注意的是，通过.detach() “分离”得到的的变量会和原来的变量共用同样的数据，而且新分离得到的张量是不可求导的，c发生了变化，原来的张量也会发生变化
c.zero_()     # 改变c的值，原来的out也会改变
print(c.requires_grad)
print(c)
print(out.requires_grad)
print(out)
print("----------------------------------------------")
 
out.sum().backward() # 对原来的out求导，
print(a.grad)  # 此时会报错，错误结果参考下面,显示梯度计算所需要的张量已经被“原位操作inplace”所更改了。

False
tensor([0., 0., 0.])
True
tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)
----------------------------------------------


RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [3]], which is output 0 of SigmoidBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

# 交叉熵测试

In [182]:
import numpy as np
# 真实值
y = np.array([1,0,0])
# 输出值
z = np.array([0.2,0.1,-0.1])
# 输出值先经过softmax
y_pred = np.exp(z) / np.exp(z).sum() # 概率之和为1
print(y_pred)
loss = (-y * np.log(y_pred)).sum()
print(loss)

[0.37797814 0.34200877 0.28001309]
0.9729189131256584


In [184]:
np.log(0.37797814)

-0.9729189157226387

In [185]:
import torch
y = torch.LongTensor([0])
z = torch.Tensor([[0.2,0.1,-0.1]])
# 不用再经过softmax，已经包含在CrossEntropyLoss里面了
criterion = torch.nn.CrossEntropyLoss()
loss = criterion(z,y)
print(loss)

tensor(0.9729)


In [180]:
import torch
criterion = torch.nn.CrossEntropyLoss(reduction='mean')
# 真实值
# longtensor表示的是第几个标签分类，第一个真实的标签是第2个类别，第二个真实标签是第0个类别，第三个真实标签是第1个类别
Y = torch.LongTensor([2,0,1])
# 预测值，线性层输出。没有经过Softmax
Y_pred1 = torch.tensor([[0.1,0.2,0.9],[1.1,0.1,0.2],[0.2,2.1,0.1]])
Y_pred2 = torch.tensor([[0.8,0.2,0.3],[0.2,0.3,0.5],[0.2,0.2,0.5]])

l1 = criterion(Y_pred1,Y)
l2 = criterion(Y_pred2,Y)

print("loss1=",l1.data,"\nloss2=",l2.data)

loss1= tensor(0.4966) 
loss2= tensor(1.2389)


In [186]:
import torch
criterion = torch.nn.CrossEntropyLoss(reduction='mean')
# 真实值
# longtensor表示的是第几个标签分类，第一个真实的标签是第0个类别，第二个真实标签是第1个类别，第三个真实标签是第2个类别
Y = torch.LongTensor([0,1,2])
# 预测值，线性层输出。没有经过Softmax
Y_pred1 = torch.tensor([[0.1,0.2,0.9],[1.1,0.1,0.2],[0.2,2.1,0.1]])
Y_pred2 = torch.tensor([[0.8,0.2,0.3],[0.2,0.3,0.5],[0.2,0.2,0.5]])

l1 = criterion(Y_pred1,Y)
l2 = criterion(Y_pred2,Y)

print("loss1=",l1.data,"\nloss2=",l2.data)

loss1= tensor(1.7633) 
loss2= tensor(0.9389)
